# Generated by Django 3.2 on 2023-01-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_initial'),
        ('titles', '0002_title_description'),
    ]

    operations = [
    ]
